version: '3'

volumes:
  postgres-data:

services:

  postgres:
    image: postgres:14-alpine3.16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: change_please
      POSTGRES_USER: dev
      POSTGRES_DB: dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data